import string


UUID_LENGTH = 36

JWT_TOKEN_NAME = 'accessToken'
JWT_REFRESH_TOKEN_NAME = 'refreshToken'

USERNAME_CHARS_WHITELIST = string.ascii_letters + string.digits + '-_.'
USERNAME_MIN_LENGTH = 2
USERNAME_MAX_LENGTH = 32

PASSWORD_MIN_LENGTH = 6

TEAM_NAME_CHARS_WHITELIST = USERNAME_CHARS_WHITELIST + ' '
TEAM_NAME_MIN_LENGTH = 2
TEAM_NAME_MAX_LENGTH = 32
TEAM_SLUG_MAX_LENGTH = 2 * TEAM_NAME_MAX_LENGTH

ISSUE_STATUS_MIN_LENGTH = 2
ISSUE_STATUS_MAX_LENGTH = 32

ISSUE_SHORT_DESCRIPTION_MIN_LENGTH = 5
ISSUE_SHORT_DESCRIPTION_MAX_LENGTH = 64
