import string


UUID_LENGTH = 36

JWT_TOKEN_NAME = 'accessToken'
JWT_REFRESH_TOKEN_NAME = 'refreshToken'

USERNAME_CHARS_WHITELIST = string.ascii_letters + string.digits
USERNAME_MIN_LENGTH = 2
USERNAME_MAX_LENGTH = 20

PASSWORD_MIN_LENGTH = 6

TEAM_NAME_CHARS_WHITELIST = string.ascii_letters + string.digits
TEAM_NAME_MIN_LENGTH = 2
TEAM_NAME_MAX_LENGTH = 20

ISSUE_STATUS_MIN_LENGTH = 2
ISSUE_STATUS_MAX_LENGTH = 20

ISSUE_SHORT_DESCRIPTION_MIN_LENGTH = 5
ISSUE_SHORT_DESCRIPTION_MAX_LENGTH = 64
