export const REQUEST_ISSUES = 'yaits/TeamPage/REQUEST_ISSUES';
export const REQUEST_ISSUES_SUCCESS = 'yaits/TeamPage/REQUEST_ISSUES_SUCCESS';
export const REQUEST_ISSUES_FAILED = 'yaits/TeamPage/REQUEST_ISSUES_FAILED';
